generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Horarioescolartipo
    theme:            default
    fields:
        id: { name: identificador }
        nombre: { name: Nombre, params: size=64}
        descripcion: { name: Descripcion, params: size=64 }
        
    edit:
        title: Modificar tipos de intervalos de horario escolar
        display: [nombre, descripcion]
                                                         
    list:
        display: [=nombre, descripcion]
        title: Listado de tipos de intervalos de horario escolar
        object_actions:
            _edit:        -
            _delete:      -

