generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Division
    theme:            default
    fields:
        anio: { name: A&ntilde;o }
        fk_anio_id: { name: A&ntilde;o }
        division: { name: Divisi&oacute;n }
        fk_turnos_id: { name: Turnos }
        descripcion: { name: Descripci&oacute;n }
        orden: { name: Orden }
    edit:
        title: Editar Divisi&oacute;n
        display: [ _fk_anio_id, descripcion, _fk_turnos_id, orden ]
                    
    list:
        title: Listado de Divisiones
        display: [ anio, descripcion, turnos, orden ]
        object_actions:
            _edit:      -
            _delete:    -
            alumnosPorDivision:  { name: Alumnos por Division, action: alumnosPorDivision, icon: small/alumnos.png }            
