generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Anio
    theme:            default
    fields:
        descripcion: { name: Descripci&oacute;n , params: size=40 }
    
    edit:
        title: " "
        display: [descripcion ]
        actions:
            _delete: -
            _save: -
            _list: -
            _save_and_add: -
                    
    list:
        title: Listado de A&ntilde;os
        display: [ =descripcion ]
        sort: descripcion
        object_actions:
            _edit:      -
            _delete:    -
