generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      RelActividadDocente
    theme:            default
    fields:
        fk_docente_id: { name: Docente }
        fk_actividad_id: { name: Actividad }
    edit:
        title: Editar Actividades del Docente
        fields:
            fk_actividad_id:   { params: include_custom=--Seleccione una Actividad--}
            fk_docente_id:   { params: include_custom=--Seleccione un Docente--}
        display: [ fk_docente_id, fk_actividad_id ]
    list:
        title: Listado de Actividades del Docente
        display: [ docente, actividad ]
        object_actions:
            _edit:      -
            _delete:    -
        actions:
            _create: -
            listadoDocente: { name: Listado de Docentes, action: listadoDocente, icon: /sf/sf_admin/images/list.png }
        filters: [ fk_actividad_id ]                                                                



