dev:
  propel:
    param:
      classname:    DebugPDO

test:
  propel:
    param:
      classname:    DebugPDO

all:
  propel:
    class:          sfPropelDatabase
    param:
      dsn:          mysql:dbname=alba;host=localhost
      username:     root
      password:     josxjosx
      enconding:    utf8
      persistent:   true
      pooling:      true
      classname:    PropelPDO
      datasource:   alba
