generator:
  class:              sfPropelAdminGenerator
  param:
      model_class:      Cuenta
      theme:            default
      fields:
            nombre: { name: Nombre, params: size=64 }
            razon_social: { name: Raz&oacute;n Social , params: size=64 }
            cuit: { name: CUIT, params: size=20 }
            direccion: { name: Direcci&oacute;n , params: size=64 }
            ciudad: { name: Ciudad, params: size=64 }
            codigo_postal: { name: CP, params: size=20  }
            fk_provincia_id: { name: Provincia }
            fk_tipoiva_id: { name: Tipo Iva } 
            telefono: { name: Tel&eacute;fono, params: size=20 }
      list:
            title: Listado de Cuentas
            display: [ _nombre, razon_social, cuit, direccion, ciudad, codigo_postal, _tipo_iva, telefono ]
            object_actions:
                _edit: -
                _delete: -
                
            actions:
                _create: -
                
      edit:
            title: Editar Cuenta
            fields:
                 fk_provincia_id:   { params: include_custom=>>Seleccione una Provincia<<}
                 fk_tipoiva_id:   { params: include_custom=>>Seleccione una Categoia de IVA<<}
            actions:
                _delete: -
                _save: -
                _list: -
                _save_and_add: -