generator:
    class:              sfPropelAdminGenerator
    param:
        model_class:      Modulo
        theme:            default

        fields:
            nombre: { name: Nombre}
            titulo: { titulo: Titulo}
            activo: { name: activo, type: checkbox_tag}    
            descripcion: { name: Descripci&oacute;n, type: textarea_tag }

        edit: 
            title: Editar Modulo
            display: [ nombre, titulo, descripcion, activo]
        
        list:
            title: Listado de Modulos
            display: [ =nombre, titulo, descripcion, activo]
            object_actions:
                _edit:        -
                _delete:      -
                                              
            