generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      RelAnioActividad
    theme:            default
    fields:
        fk_anio_id: { name: A&ntilde;o }
        anio: { name: A&ntilde;o }
        fk_actividad_id: { name: Actividad }
        horas: { name: Horas Semanales }
    edit:
        title: Editar Actividades del A&ntilde;o
        fields:
            fk_anio_id:   { params: include_custom=--Seleccione un Añ--<}
            fk_actividad_id:   { params: include_custom=>>Seleccione una Actividad<<}
        display: [ fk_anio_id, fk_actividad_id, horas ]
    list:
        title: Listado de Actividades por A&ntilde;o
        display: [ anio, actividad, horas ]
        object_actions:
            _edit:      -
            _delete:    -
        filters: [ fk_anio_id ]                                                                
